name: Run brownfield land collection

on:
  push:
    paths-ignore:
      - 'collection/**'
      - 'validation/**'
      - 'var/**'
      - 'index/**'
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

env:
  DLB_BOT_EMAIL: ${{ secrets.DLB_BOT_EMAIL }}
  DLB_BOT_TOKEN: ${{ secrets.DLB_BOT_TOKEN }}
  DLB_BOT_USERNAME: ${{ secrets.DLB_BOT_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup git
      run: |
        git config user.email "${DLB_BOT_EMAIL}"
        git config user.name "${DLB_BOT_USERNAME}"
        git remote set-url origin https://${DLB_BOT_USERNAME}:${DLB_BOT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
    - name: Install dependencies
      run: make init
    - name: Collect resources
      run: make collect
    - name: Commit resources
      run: |
        git add collection
        git diff --quiet && git diff --staged --quiet || (git commit -m "Commit files collected on $(date +%F)"; git push origin master)
    - name: Validate resources
      run: make validate
    - name: Commit validation output
      run: |
        git add validation
        git diff --quiet && git diff --staged --quiet || (git commit -m "Commit files validated on $(date +%F)"; git push origin master)
    - name: Harmonise files, create dataset and index
      run: make harmonise dataset index
    - name: Commit harmonised files, dataset and indexes
      run: |
        git add var index
        git diff --quiet && git diff --staged --quiet || (git commit -m "Commit new dataset and indexes for $(date +%F)"; git push origin master)
